FROM {{ string "docker.baseImage" .Vars }}:{{ string "docker.baseTag" .Vars }} as builder
COPY main.go /go
RUN go build -v -o app

FROM scratch

COPY --from=builder /go/app /app

ENTRYPOINT [ "/app" ]
USER 1000
