FROM {{ string "docker.baseImage" .Vars }}:{{ string "docker.baseTag" .Vars }} as builder
COPY main.go /go
RUN go build -v -o app


FROM scratch

COPY --from=builder /go/app /app

ENTRYPOINT [ "/app" ]


# production runner
FROM {{string "docker.image" .Vars | default "scratch"}}
WORKDIR /{{$service}}

CMD ["./{{$service}}"]

COPY buildInfo.json .
COPY Gopkg.lock .
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /tmp/builds/* ./

USER 1000%